services:
  core-api:
    build: .
    container_name: core-api-dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8081:8080"
    volumes:
      - ~/projects/core-api:/app
    command: npm run dev 