version: '3.8'

services:
  storyseeker-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app  
    command: npm run dev 