name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t core-api .

      - name: Tag Docker image
        run: |
          docker tag core-api "${{ secrets.DOCKER_USERNAME }}/core-api:latest"

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/core-api:latest"

      - name: SSH to server and run Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |  
            docker pull "${{ secrets.DOCKER_USERNAME }}/core-api:latest"
            
            docker stop core-api || true
            docker rm core-api || true
            
            docker run -d \
              --restart unless-stopped \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              -e NODE_ENV=production  \
              -p 8080:8080 \
              --name core-api \
              ${{ secrets.DOCKER_USERNAME }}/core-api:latest
